# Generated by Django 3.1.5 on 2021-01-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_cropstage_problem_problemtopic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='CropSeason',
        ),
        migrations.DeleteModel(
            name='CropStage',
        ),
        migrations.DeleteModel(
            name='CropVariety',
        ),
    ]
