# Generated by Django 3.1.5 on 2021-03-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210129_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltype',
            name='bn_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
