# Generated by Django 3.1.5 on 2021-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_soiltype_bn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtype',
            name='bn_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
