# Generated by Django 3.1.5 on 2021-01-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210124_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='metropolitan',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
